### ISSUE TITLE
Slash missing

### ISSUE THREAD

**Issue by cukal** [michael-doubez/filestat_exporter#11]
It seems a final slash is missing on all the output:  

filestat.yml:

```
exporter:
  #! Working directory of exporter
  working_directory: "/dir1/dir2/dir3/"

  #! Network parameters
  #listen_address: ':9943'
  #metrics_path: /metrics

  #! Uncomment one of the following to enable default config
  #enable_crc32_metric: true
  #enable_nb_line_metric: true

  # list of patterns to apply
  files:
    - patterns: ["*/*/.ERROR"]
    - patterns: ["*/*/*.ERROR"]
    - patterns: ["*/*/*/*.ERROR"]
```

Metric output: 

```
file_glob_match_number{pattern="*/*/*.ERROR"} 294
file_glob_match_number{pattern="*/*/*/*.ERROR"} 36
file_glob_match_number{pattern="*/*/.ERROR"} 0
file_stat_size_bytes{path="dir/dir/dir20201208164827.xml.ERROR"} 171
file_stat_size_bytes{path="dir/dir/dir20201208165023.xml.ERROR"} 17
```

The files are actually located at: 

```
/dir1/dir2/dir3/dir/dir/dir/20201208164827.xml.ERROR
/dir1/dir2/dir3/dir/dir/dir/20201208165023.xml.ERROR
```

Between the filename and the last directory a slash seems missing.
Is this expected, an issue with configuration, a bug or me not understanding something?

Thanks!
