### ISSUE TITLE
Files in different directories

### ISSUE THREAD

**Issue by s5unty** [michael-doubez/filestat_exporter#17]
Is there any way to monitor files in different directories? For example

- /etc/passwd
- /data/blabla

**Comment by michael-doubez** [comment]
You can set a working directory to the root and adapt the patterns:

```yaml
exporter:
  working_directory: "/"
  files:
    - patterns: ["/etc/passwd"]
    - patterns: ["/data/blabla/*.html"]
```

Otherwise, you can create a directory for monitoring and create symlinks (not tested):

```
mkdir /var/monitoring/
cd /var/monitoring/
ln -s /etc/
ln -s /data/
```

Then 

```yaml
exporter:
  working_directory: "/var/monitoring"
  # Default enable/disable of metrics - overridden if not set by parameter '-metric.*'
  enable_crc32_metric: true
  # enable_nb_line_metric: false
  # list of patterns to apply - metrics can be enable/disabled for each group
  files:
    - patterns: ["etc/passwd"]
    - patterns: ["data/blabla/*.html"]
```

**Comment by michael-doubez** [comment]
On second thought, I never enforced that files should be relative to working dir.

So you can simply add `/etc/password` to its own pattern:

```yaml
exporter:
  files:
    - patterns: ["/etc/passwd"]
    - patterns: ["*.html"]
```

**Comment by s5unty** [comment]
```
% tree /tmp/today/monit
/tmp/today/monit
|-- passwd -> /etc/passwd
`-- syslog -> /var/log/syslog

% cat filestat.yaml
exporter:
# working_directory: "/tmp/today/monit/"  # this is OK
  working_directory: "/tmp/"              # this is not OK
  files:
     - patterns: ["/var/log/syslog"]
     - patterns: ["/etc/passwd"]

% ./filestat_exporter --version
filestat_exporter, version v0.3.3 (branch: HEAD, revision: e9f967b)
  build user:
  build date:       2021-07-21T20:09:17+0000
  go version:       go1.16.6
  platform:         linux/amd64
```

Thanks for the quick reply, I'll check again, thanks.

**Comment by Leif160519** [comment]
Hi, I found that this writing method below works on version 0.3.2, but will have problems recognizing it on version 0.3.3
```
exporter:
  listen_address: ':9943'
  metrics_path: /metrics
  enable_crc32_metric: true
  working_directory: "/"
  files:
    - patterns: ["/var/backups/bala.txt","/etc/passwd"]
      enable_crc32_metric: true
      enable_nb_line_metric: true
```

0.3.3 effect:
```
file_glob_match_number{pattern="/etc/passwd"} 1
file_glob_match_number{pattern="/var/backups/bala.txt"} 1
```

0.3.2 effect:
```
file_glob_match_number{pattern="/etc/passwd"} 0
file_glob_match_number{pattern="/var/backups/mysql.bak"} 0
```
