### ISSUE TITLE
Add the option for labels

### ISSUE THREAD

**Issue by teejaybugge** [michael-doubez/filestat_exporter#44]
Thanks for a nice metric exporter.

Would it be possible to add labels for each pattern in the config?

E.g.:

```
files:
    - patterns: ["*.html","assets/*.css","scripts/*.js"]
         labels:
            region: eu
            env: env1
    - patterns: ["data/*.csv"]
         labels:
            region: us
            env: env2
```
